import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://rahulshettyacademy.com/angularpractice/');
  await page.locator('form input[name="name"]').click();
  await page.locator('form input[name="name"]').press('CapsLock');
  await page.locator('form input[name="name"]').fill('R');
  await page.locator('form input[name="name"]').press('CapsLock');
  await page.locator('form input[name="name"]').fill('Rabeeh');
  await page.locator('input[name="email"]').click();
  await page.locator('input[name="email"]').fill('set@gmail.com');
  await page.getByRole('checkbox', { name: 'Check me out if you Love' }).check();
  await page.getByLabel('Gender').selectOption('Female');
  await page.locator('div').filter({ hasText: 'Employed' }).nth(2).click();
  await page.getByRole('radio', { name: 'Employed' }).check();
  await page.locator('input[name="bday"]').fill('1994-02-11');
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page.getByText('× Success! The Form has been')).toBeVisible();
  await page.getByRole('link', { name: 'Shop' }).click();
  await page.locator('app-card').filter({ hasText: 'iphone X $24.99 Lorem ipsum' }).getByRole('button').click();
  await page.locator('app-card').filter({ hasText: 'Samsung Note 8 $24.99 Lorem' }).getByRole('button').click();
  await expect(page.locator('#navbarResponsive')).toContainText('Checkout ( 2 ) (current)');
  await page.getByText('Checkout ( 2 ) (current)').click();
  await expect(page.getByRole('link', { name: 'iphone X' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Samsung Note' })).toBeVisible();
  await page.getByRole('button', { name: 'Checkout' }).click();
  await page.getByRole('textbox', { name: 'Please choose your delivery' }).click();
  await page.getByRole('textbox', { name: 'Please choose your delivery' }).fill('india');
  await page.getByText('I agree with the term &').click();
  await page.getByRole('checkbox', { name: 'I agree with the term &' }).check();
  await expect(page.getByRole('textbox', { name: 'Please choose your delivery' })).toHaveValue('india');
  await expect(page.locator('app-checkout')).toContainText('Please choose your delivery location. Then click on purchase button');
  await page.getByRole('button', { name: 'Purchase' }).click();
  await expect(page.getByText('× Success! Thank you! Your')).toBeVisible();
});